# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: vincent.kruit@dtc.ox.ac.uk
full_name: VincentKruit
license: MIT
min_python_version: '3.10'
org: Vincentdtc
project_name: project1
project_short_description: A great package.
python_name: project1
typing: no_typing
url: https://github.com/Vincentdtc/project1
